"""crear modelos iniciales

Revision ID: 3c62c2b3a110
Revises: 
Create Date: 2026-09-02 10:44:19.892600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c62c2b3a110'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('uid_rfid', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('uid_rfid')
    )
    op.create_table('tipos_equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('tipo_equipo_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['tipo_equipo_id'], ['tipos_equipo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('sesiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_accesorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_equipo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cantidad_default', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_equipo_id'], ['tipos_equipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sesion_equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_prestamo', sa.DateTime(), nullable=False),
    sa.Column('fecha_devolucion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fallas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('sesion_equipo_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('observacion_resolucion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['sesion_equipo_id'], ['sesion_equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sesion_equipo_accesorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_equipo_id', sa.Integer(), nullable=False),
    sa.Column('tipo_accesorio_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_prestada', sa.Integer(), nullable=False),
    sa.Column('cantidad_devuelta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sesion_equipo_id'], ['sesion_equipos.id'], ),
    sa.ForeignKeyConstraint(['tipo_accesorio_id'], ['tipos_accesorio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sesion_equipo_accesorios')
    op.drop_table('fallas')
    op.drop_table('sesion_equipos')
    op.drop_table('tipos_accesorio')
    op.drop_table('sesiones')
    op.drop_table('equipos')
    op.drop_table('tipos_equipo')
    op.drop_table('estudiantes')
    # ### end Alembic commands ###
